[package]
name = "sevro"
version = "0.1.0"
edition = "2024"
license = "BSD-3-Clause"
readme = "README.md"

[lib]
name = "core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module", "generate-import-lib", "experimental-async"] }
pyo3-async-runtimes = { version = "0.27.0", features = ["tokio-runtime"] }
hyper = { version = "1.8.1", features = ["full"] }
hyper-util = { version = "0.1.19", features = ["full"] }
thiserror = "2.0.18"
url = "2.5.8"
form_urlencoded = "1.2.2"
