from typing import MutableMapping, Any, Iterator


class Headers:
    def __contains__(self, key: str) -> bool: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[str]: ...
    def items(self) -> list[tuple[str, str]]: ...
    def get(self, key: str, default: Any = None) -> Any: ...

class Scope:
    proto: str
    http_version: str
    rsgi_version: str
    server: str
    client: str
    scheme: str
    method: str
    path: str
    query_string: str
    authority: str | None

    @property
    def headers(self) -> Headers: ...

class StreamTransport:
    async def send_bytes(self, data: bytes) -> None: ...
    async def send_str(self, data: str) -> None: ...

class Protocol:
    async def __call__(self) -> bytes: ...
    def __aiter__(self) -> Any: ...
    async def client_disconnect(self) -> None: ...
    def response_empty(self, status: int, headers: list[tuple[str, str]]) -> None: ...
    def response_str(self, status: int, headers: list[tuple[str, str]], body: str) -> None: ...
    def response_bytes(self, status: int, headers: list[tuple[str, str]], body: bytes) -> None: ...
    def response_file(self, status: int, headers: list[tuple[str, str]], file: str) -> None: ...
    def response_file_range(
            self, status: int, headers: list[tuple[str, str]], file: str, start: int, end: int
    ) -> None: ...
    def response_stream(self, status: int, headers: list[tuple[str, str]]) -> StreamTransport: ...

class WebsocketMessage:
    kind: int
    data: bytes | str

class WebsocketTransport:
    async def receive(self) -> WebsocketMessage: ...
    async def send_bytes(self, data: bytes) -> None: ...
    async def send_str(self, data: str) -> None: ...

class WebsocketProtocol:
    async def accept(self) -> WebsocketTransport: ...
    def close(self, status: int | None) -> tuple[int, bool]: ...