from typing import Callable, Any


class URL:
    def __new__(cls, url: str) -> "URL": ...
    def scheme(self) -> str | None: ...
    def host(self) -> str | None: ...
    def port(self) -> int | None: ...
    def path(self) -> str: ...
    def query_string(self) -> str | None: ...
    def query(self) -> dict[str, str]: ...

class Router:
    def route(self, method: str, pattern: str, fn: Callable[..., Any]) -> None: ...
    def find(self, method: str, path: str) -> tuple[Callable[..., Any], dict[str, str]] | None: ...