class Router[T]:
    def __new__(cls) -> "Router[T]": ...
    def get(self, path: str, handler: T) -> None: ...
    def post(self, path: str, handler: T) -> None: ...
    def put(self, path: str, handler: T) -> None: ...
    def delete(self, path: str, handler: T) -> None: ...
    def patch(self, path: str, handler: T) -> None: ...
    def head(self, path: str, handler: T) -> None: ...
    def options(self, path: str, handler: T) -> None: ...
    def route(self, methods: list[str], path: str, handler: T) -> None: ...
    def find(self, path: str, method: str) -> tuple[T, dict[str, str]] | None: ...
