from sevro._types import Scope

class URL:
    def __new__(cls, url: str) -> "URL": ...
    def scheme(self) -> str | None: ...
    def host(self) -> str | None: ...
    def port(self) -> int | None: ...
    def path(self) -> str: ...
    def query_string(self) -> str | None: ...
    def query(self) -> dict[str, str]: ...

def parse(url: str) -> URL: ...
def from_scope(scope: Scope) -> URL: ...
